BASE_CONFIDENCE = {
    "BUY-UPTREND-LOW-PE": 90,
    "BUY-UPTREND-FAIR-PE": 82,
    "BUY-UPTREND-HIGH-VOLUME": 95,

    "HOLD-SIDEWAYS-POSITIVE-EARNINGS": 75,
    "HOLD-UPTREND-LOW-PE-NEUTRAL-REVENUE": 72,
    "HOLD-UPTREND-FAIR-PE-NEUTRAL-REVENUE": 68,
    "HOLD-DOWNTREND-NEUTRAL-REVENUE": 65,
    "HOLD-DOWNTREND-POSITIVE-FUNDAMENTALS": 70,
    "HOLD-DOWNTREND-MIXED-FUNDAMENTALS": 60,
    "HOLD-UPTREND-LOW-VOLUME": 78,

    "SELL-DOWNTREND-NEGATIVE-FUNDAMENTALS": 90,
    "SELL-SIDEWAYS-NEGATIVE-EARNINGS": 80,
    "SELL-DOWNTREND-HIGH-PE": 82,
    "SELL-DOWNTREND-NEGATIVE-EARNINGS": 78,

    "NO-CLEAR-RECOMMENDATION": 0,
}

def get_base_confidence(rule):
    return BASE_CONFIDENCE.get(rule, 0)